# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpenses',
            name='expense_description',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
