# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_userexpenses_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpenses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
