# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_auto_20170823_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpenses',
            name='expense_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 6, 32, 53, 587769)),
        ),
    ]
